---
- include_vars: uf_user_password.yml

- name: Check if Splunk already installed
  stat:
    path: '/opt/splunkforwarder'
  register: splunk_path_present

- block:
  - name: Quit if Splunk UF already installed
    debug:
      msg: "Splunk UF already installed, exiting"
  - meta: end_play
    when: splunk_path_present.stat.exists == true

- name: Check if Splunk forwarder package already transferred - CentOS
  stat:
    path: "{{splunk_working_directory}}{{splunk_uf_file_rpm}}"
  register: splunk_installer_present
  when:
    - ansible_facts['distribution'] == "CentOS"
 
- name: Check if Splunk forwarder package already transferred - Non CentOS
  stat:
    path: "{{splunk_working_directory}}{{splunk_uf_file_deb}}"
  register: splunk_installer_present
  when:
    - ansible_facts['distribution'] != "CentOS"

- name: Copy installer over to system - CentOS
  copy:
    src: "{{splunk_uf_file_rpm}}"
    dest: "{{splunk_working_directory}}"
    owner: eingram
    group: eingram
    mode: 0644
  when:
    - splunk_installer_present.stat.exists == false
    - splunk_path_present.stat.exists == false
    - ansible_facts['distribution'] == "CentOS"
 
- name: Copy installer over to system - Non CentOS
  copy:
    src: "{{splunk_uf_file_deb}}"
    dest: "{{splunk_working_directory}}"
    owner: eingram
    group: eingram
    mode: 0644
  when:
    - splunk_installer_present.stat.exists == false
    - splunk_path_present.stat.exists == false
    - ansible_facts['distribution'] != "CentOS"

- name: Copy user-seed.conf to Forwarder Location
  copy:
    src: user-seed.conf
    dest: /opt/splunkforwarder/etc/system/local/
    owner: eingram
    group: eingram
    mode: 0666
  become: true

- name: Install Splunk UF Package - CentOS
  yum:
    name: "{{splunk_working_directory}}{{splunk_uf_file_rpm}}"
    state: present
  become: true
  when:
    - splunk_path_present.stat.exists == false
    - ansible_facts['distribution'] == "CentOS"
 
- name: Install Splunk UF Package - Non CentOS
  apt:
    deb: "{{splunk_working_directory}}{{splunk_uf_file_deb}}"
  become: true
  when:
    - splunk_path_present.stat.exists == false
    - ansible_facts['distribution'] != "CentOS"

- name: Install acl package for setfacl (CentOS)
  yum:
    name: acl
    state: present
  when: ansible_facts['distribution'] == "CentOS"

- name: Install acl package for setfacl (non CentOS)
  apt:
    name: acl
    state: present
  when: ansible_facts['distribution'] != "CentOS"

- name: Allow splunk access to log files
  become: true
  shell: |
    /usr/bin/setfacl -m "u:splunk:r-x" /var/log
    /usr/bin/setfacl -m "u:splunk:r--" /var/log/*
    /usr/bin/setfacl -m d:user:splunk:r /var/log
#    /usr/bin/setfacl -m "u:splunk:r-x" /etc
#    /usr/bin/setfacl -m "u:splunk:r--" /etc/*
    
- name: Start Splunk Forwarder
  become: true
  ansible.builtin.shell: /opt/splunkforwarder/bin/splunk start --accept-license

- name: Set Deployment Server
  become: true
  command: /opt/splunkforwarder/bin/splunk set deploy-poll -auth splunk:{{uf_user_password}} splunk.local.lan:8089

- name: Set forward-server
  become: true
  command: /opt/splunkforwarder/bin/splunk add forward-server -auth splunk:{{uf_user_password}} splunk.local.lan:9997
 
- name: Stopping Splunk to enable boot start
  become: true
  ansible.builtin.shell: /opt/splunkforwarder/bin/splunk stop

- name: Change ownership of Splunk files to splunk user
  ansible.builtin.file:
    path: /opt/splunkforwarder
    state: directory
    recurse: yes
    owner: splunk
    group: splunk
  become: true
    
- name: Enable Boot Start
  become: true
  command: /opt/splunkforwarder/bin/splunk enable boot-start -user splunk -systemd-managed 1
 
- name: Restart Splunk forwarder
  become: true
  command: /opt/splunkforwarder/bin/splunk restart
...